"""Stats + bar verdict (PROTOCOL S6). Run AFTER grades.csv is filed; this UNSEALS the mapping.
grades.csv columns: answer_id,task,score,penalties,justification (score 0-3 int; penalties <=0 int).
spend CSV (optional): arm,task,tokens_in,tokens_out,usd. Usage: python ws4_stats.py <RUN_ID>
"""
import json, sys, itertools, random
import pandas as pd
from pathlib import Path

ROOT = Path(r"c:\Users\Shreyas.1Gupta\OneDrive - Angel Broking Limited\Desktop\Backup\NIFTY 500")
RUN = ROOT / "Shreyas_Ionic_AMC/04_RND_LAB/SYSTEM_SCIENCE_PROGRAM/ws4_battery/results" / sys.argv[1]
CLEAN = {"T03", "T07", "T14", "T19"}
g = pd.read_csv(RUN / "grades.csv")
mapping = json.loads((RUN / "_mapping.json").read_text(encoding="utf-8"))
g["arm"] = g.answer_id.map(lambda r: mapping[r]["arm"])
g["net"] = g.score.clip(0, 3) + g.penalties.clip(upper=0)
g["defective"] = ~g.task.isin(CLEAN)
assert g.groupby("arm").size().min() >= 20, "missing (arm,task) grades"

rows = {}
for arm, gg in g.groupby("arm"):
    d = gg[gg.defective]
    c = gg[~gg.defective]
    rows[arm] = dict(
        n=len(gg),
        defects_found=int((d.score >= 2).sum()),
        mean_score=round(float(d.net.mean()), 3),
        clean_fp_rate=round(float((c.penalties < 0).sum() / len(c)), 3),
        clean_correct=int(((c.score >= 2) & (c.penalties == 0)).sum()),
    )
res = pd.DataFrame(rows).T
print(res.to_string())

def perm_p(a, b, n=20000, seed=7):
    # paired sign-flip on per-task defects-found indicator (defective tasks only)
    da = g[(g.arm == a) & g.defective].set_index("task").score.ge(2).astype(int).sort_index()
    db = g[(g.arm == b) & g.defective].set_index("task").score.ge(2).astype(int).sort_index()
    obs = (da - db).sum()
    rng = random.Random(seed)
    diffs = da - db
    cnt = 0
    for _ in range(n):
        s = sum(d if rng.random() < 0.5 else -d for d in diffs)
        if abs(s) >= abs(obs):
            cnt += 1
    return obs, cnt / n

lines = [res.to_string(), ""]
for a, b in itertools.combinations(sorted(rows), 2):
    obs, p = perm_p(a, b)
    lines.append(f"paired sign-flip {a} vs {b}: diff(defects)={obs:+d}, p={p:.4f} (supporting, not gating)")

# frozen bar (PROTOCOL S6): C >= 1.2 x max(A, B) on defects_found
if all(k in rows for k in "ABC"):
    need = 1.2 * max(rows["A"]["defects_found"], rows["B"]["defects_found"])
    ok = rows["C"]["defects_found"] >= need
    fp_note = ""
    if ok and rows["C"]["clean_fp_rate"] > rows["B"]["clean_fp_rate"]:
        fp_note = " CAVEAT (must be prominent): C's clean-task FP rate is WORSE than B's."
    lines.append(f"FROZEN BAR: C defects {rows['C']['defects_found']} vs required >= {need:.1f} -> {'BAR MET' if ok else 'BAR NOT MET'}.{fp_note}")
spend = RUN / "spend.csv"
if spend.exists():
    s = pd.read_csv(spend).groupby("arm")[["tokens_in", "tokens_out", "usd"]].sum()
    s["score_per_usd"] = [round(rows[a]["mean_score"] / max(u, 1e-9), 2) if a in rows else None for a, u in zip(s.index, s.usd)]
    lines.append("\n" + s.to_string())
out = "\n".join(lines)
(RUN / "RESULTS.md").write_text("# WS-4 RESULTS (auto-generated by ws4_stats.py)\n\n```\n" + out + "\n```\n", encoding="utf-8")
print(out)
print("\nRESULTS.md written. Fill paper Tables 1-6 + LinkedIn [RESULT] slots from this file ONLY.")
